---
slug: openshift-labguide
filename: openshift-labguide
title: Openshift Labguides
subtitle: Learn Openshift step by step
description: This is a step by step guide with hands on exercises to learn  Kubernetes and Openshift, a containers orchestration platform.
author: Gourav Shah
copyright: 2017
uuid: 74ea259c-dd83-4b9a-8bc2-99d04de57d79
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
